### ISSUE TITLE
xml não pode ser lido

### ISSUE THREAD

**Issue by dan-alarcon** [monteirosk/sinesp-client-php#3]
Monteiro, 
infelizmente continuo com problema...
Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /home/storage/1/3a/c2/blablabla/public_html/index.php:65 Stack trace: #0 /home/storage/1/3a/c2/blablabla/public_html/index.php(65): SimpleXMLElement->__construct('') #1 {main} thrown in /home/storage/1/3a/c2/blablabla/public_html/index.php on line 65

Existe uma versão adequada para o php?
Abraços

**Comment by dan-alarcon** [comment]
Versão do PHP

**Comment by monteirosk** [comment]
![00001](https://user-images.githubusercontent.com/1817334/53259944-bfb08b00-36a6-11e9-90b1-5c97a5752d27.png)

**Comment by monteirosk** [comment]
só funciona em ip brasileiro

**Comment by dan-alarcon** [comment]
Obrigado, Monteiro!
Bom final de semana!

**Comment by monteirosk** [comment]
Deu certo ?

**Comment by dan-alarcon** [comment]
Deu,  muito obrigado! 
A versão do Php tem que ser 7!
O seu código é o melhor!!!!
